const REVIEW_URL='https://maps.app.goo.gl/haWqCKfQQN6azjuAA?g_st=ic';
document.querySelector('input[name="date"]').min=new Date().toISOString().slice(0,10);
const vehicles={small:{name:'Hatchback / Small Car',examples:'Yaris, Golf, i30, Mazda 2'},sedan:{name:'Sedan',examples:'Camry, Mazda 3, Elantra, Accord'},medium:{name:'Compact / Medium SUV',examples:'RAV4, CR-V, CX-5, Tucson'},large:{name:'Large SUV / 7-Seater / Ute',examples:'Kluger, Prado, Ranger, Hilux'},prestige:{name:'Prestige / Exotic / Supercar',examples:'Porsche, Ferrari, Lamborghini, BMW M, Mercedes-AMG'}};
const packages={essential:{name:'Peak Essential',tag:'Maintenance detail',prices:{small:150,sedan:200,medium:250,large:300},scope:['Exterior hand wash','Wheels and tyre faces cleaned','Wheel arches rinsed','Exterior and interior glass','Full interior vacuum','Dashboard, console and door-panel wipe','Light door-jamb wipe','Tyre dressing and finishing spray','Complimentary air freshener']},premium:{name:'Peak Premium',tag:'Deep interior + exterior',prices:{small:250,sedan:300,medium:350,large:400},scope:['Detailed interior and boot vacuum','Carpet and fabric extraction where required','Steam cleaning on suitable surfaces','Detailed dashboard, console and door panels','Detailed door-jamb clean','Light stain and odour treatment','Snow-foam pre-wash and contact wash','Wheels, arches and fuel area detailed','Tyre dressing and gloss protection']},ultimate:{name:'Peak Ultimate',tag:'Complete detail + single-stage polish',prices:{small:550,sedan:650,medium:750,large:850},scope:['Peak Premium interior and exterior detail','Chemical and mechanical decontamination','Iron-particle removal where required','Clay-bar or clay-towel treatment','Paint inspection and preparation','Single-stage machine polish','Improves light swirls and mild oxidation','Paint sealant and final gloss treatment']},prestige:{name:'Prestige / Exotic',tag:'White-glove custom service',prices:{prestige:null},scope:['Tailored service plan','Paint-safe pH-neutral products','Dedicated detailer','Pre- and post-service condition report','Custom quote after scope discussion']}};
const addons=[['engine','Engine-bay detailing',80],['clay','Full-vehicle clay decontamination',80],['leather','Leather clean and condition',80],['pet','Pet-hair removal',50],['bio','Biological contamination treatment',100],['odour','Odour-neutralising treatment',60],['headlights','Headlight restoration (pair)',100],['shampoo','Selected seat or carpet shampoo',80],['stain','Heavy stain treatment',40],['contamination','Bug, tar or tree-sap removal',40]];
const flags=[['pet','Pet hair'],['stain','Heavy stains'],['sand','Sand, mud or food debris'],['odour','Strong odour'],['bio','Biological contamination'],['mould','Mould'],['paint','Paint needs gloss improvement'],['prestige','Prestige or exotic vehicle']];
let step=1; let recommended='essential';
const form=document.querySelector('#bookingForm');
const money=n=>n==null?'Custom quote':new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD',maximumFractionDigits:0}).format(n);
document.querySelector('#vehicleOptions').innerHTML=Object.entries(vehicles).map(([id,v])=>`<label class="select-card"><input type="radio" name="vehicleSize" value="${id}" required><span><strong>${v.name}</strong><small>${v.examples}</small></span><b>${id==='prestige'?'POA':`From ${money(packages.essential.prices[id])}`}</b></label>`).join('');
document.querySelector('#conditionFlags').innerHTML=flags.map(([id,label])=>`<label class="select-card"><input type="checkbox" name="flags" value="${id}"><span><strong>${label}</strong></span></label>`).join('');
document.querySelector('#addonOptions').innerHTML=addons.map(([id,name,price])=>`<label class="addon-card"><input type="checkbox" name="addons" value="${id}"><span><strong>${name}</strong><small>Starting price</small></span><b>From ${money(price)}</b></label>`).join('');

function data(){const fd=new FormData(form),result=Object.fromEntries([...fd.keys()].map(k=>[k,fd.getAll(k).length>1?fd.getAll(k):fd.get(k)]));result.customerName=[result.firstName,result.lastName].filter(Boolean).join(' ').trim();result.address=[result.streetAddress,result.suburb,result.postcode].filter(Boolean).join(', ');return result;}
function packagePrice(pkg,size){return packages[pkg]?.prices[size]??null}
function recommend(){const d=data();const f=[].concat(d.flags||[]);if(d.vehicleSize==='prestige'||f.includes('prestige'))recommended='prestige';else if(f.includes('paint'))recommended='ultimate';else if(d.condition==='heavy'||f.some(x=>['bio','mould'].includes(x)))recommended='premium';else if(d.condition==='moderate'||f.some(x=>['pet','stain','sand','odour'].includes(x)))recommended='premium';else recommended='essential';return recommended}
function renderPackages(){const size=data().vehicleSize;recommend();document.querySelector('#packageOptions').innerHTML=Object.entries(packages).filter(([id])=>size==='prestige'?id==='prestige':id!=='prestige').map(([id,p])=>`<label class="package-card ${id===recommended?'recommended':''}"><input type="radio" name="package" value="${id}" ${id===recommended?'checked':''} required><span><strong>${p.name}</strong><small>${p.tag}</small></span><b>${money(packagePrice(id,size))}</b></label>`).join('');const p=packages[recommended];document.querySelector('#recommendation').innerHTML=`<strong>We recommend ${p.name}</strong><p>${recommendationReason()}</p>`;renderComparison();updatePrice()}
function recommendationReason(){const d=data(),f=[].concat(d.flags||[]);if(recommended==='prestige')return 'Prestige and exotic vehicles receive a tailored scope and custom quote.';if(recommended==='ultimate')return 'You selected paint improvement, so a complete detail with single-stage machine polish is the best fit.';if(recommended==='premium')return d.condition==='heavy'||f.includes('bio')||f.includes('mould')?'The vehicle needs inspection and a deeper service. Premium is the starting recommendation; severe contamination may require a custom price.':'Your vehicle needs more than a maintenance wipe, including deeper interior or exterior treatment.';return 'Your vehicle sounds regularly maintained with light dirt and no major contamination.'}
function renderComparison(){const chosen=data().package||recommended,p=packages[chosen];document.querySelector('#packageComparison').innerHTML=`<strong>${p.name} includes:</strong><ul>${p.scope.map(x=>`<li>${x}</li>`).join('')}</ul>`}
function selectedAddons(){const selected=[].concat(data().addons||[]);return addons.filter(x=>selected.includes(x[0]))}
function updatePrice(){const d=data(),pkg=d.package||recommended,size=d.vehicleSize;let base=packagePrice(pkg,size);let extras=selectedAddons().reduce((s,x)=>s+x[2],0);document.querySelector('#livePrice').textContent=base==null?(size?'Custom quote':'Select a vehicle'):`From ${money(base+extras)}`;document.querySelector('#livePackage').textContent=packages[pkg]?.name||'No package selected'}
function showStep(n){step=n;document.querySelectorAll('.form-step').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===n));document.querySelector('#stepLabel').textContent=`Step ${n} of 6`;document.querySelector('#progressBar').style.width=`${n/6*100}%`;document.querySelector('#backBtn').hidden=n===1;document.querySelector('#nextBtn').hidden=n===6;document.querySelector('#submitBtn').hidden=n!==6;if(n===3)renderPackages();if(n===6)renderSummary();window.scrollTo({top:document.querySelector('.booking-shell').offsetTop-90,behavior:'smooth'})}
function validateStep(){const current=document.querySelector(`.form-step[data-step="${step}"]`),error=document.querySelector('#stepError');let ok=true,firstInvalid=null;current.querySelectorAll('[required]').forEach(el=>{let valid=el.type==='radio'?[...current.querySelectorAll(`[name="${el.name}"]`)].some(x=>x.checked):el.checkValidity();el.classList.toggle('error',!valid);if(!valid){ok=false;firstInvalid??=el}});if(ok){error.hidden=true;error.textContent='';return true}const utilities=current.querySelector('input[name="utilities"]');error.textContent=utilities&&!utilities.checked?'Please confirm that water and electricity are available before continuing.':'Please complete the highlighted required information before continuing.';error.hidden=false;firstInvalid?.focus({preventScroll:true});error.scrollIntoView({behavior:'smooth',block:'center'});return false}
function renderSummary(){const d=data(),pkg=d.package||recommended,size=d.vehicleSize,base=packagePrice(pkg,size),extra=selectedAddons().reduce((s,x)=>s+x[2],0);const addonText=selectedAddons().length?selectedAddons().map(x=>x[1]).join(', '):'None selected';document.querySelector('#orderSummary').innerHTML=`<div class="summary-row"><span>Customer</span><strong>${escapeHtml(d.customerName)}</strong></div><div class="summary-row"><span>Vehicle</span><strong>${escapeHtml([d.year,d.make,d.model].filter(Boolean).join(' '))} · ${vehicles[size].name}</strong></div><div class="summary-row"><span>Recommended selection</span><strong>${packages[pkg].name}</strong></div><div class="summary-row"><span>Add-ons</span><strong>${addonText}</strong></div><div class="summary-row"><span>Appointment request</span><strong>${escapeHtml(d.date)} · ${escapeHtml(d.time)}</strong></div><div class="summary-row"><span>Payment</span><strong>${escapeHtml(d.payment)}</strong></div><div class="summary-row summary-total"><span>Estimated starting total</span><strong>${base==null?'Custom quote':money(base+extra)}</strong></div>`}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
document.querySelector('#nextBtn').addEventListener('click',()=>{if(!validateStep())return;if(step===2)recommend();showStep(step+1)});document.querySelector('#backBtn').addEventListener('click',()=>showStep(step-1));form.addEventListener('change',e=>{if(e.target.name==='package')renderComparison();updatePrice()});
form.addEventListener('submit',async e=>{e.preventDefault();if(!validateStep())return;const btn=document.querySelector('#submitBtn');btn.disabled=true;btn.textContent='Sending…';const d=data(),order=`PF-${new Date().toISOString().slice(2,10).replaceAll('-','')}-${Math.random().toString(36).slice(2,6).toUpperCase()}`,pkg=d.package||recommended,size=d.vehicleSize,base=packagePrice(pkg,size),extra=selectedAddons().reduce((s,x)=>s+x[2],0),record={...d,package:pkg,order,status:'Awaiting confirmation',estimatedTotal:base==null?null:base+extra,createdAt:new Date().toISOString(),reviewUrl:REVIEW_URL};try{await window.PeakDB.createBooking(record);form.hidden=true;document.querySelector('.progress-head').hidden=true;document.querySelector('.progress-track').hidden=true;document.querySelector('#successPanel').hidden=false;document.querySelector('#successName').textContent=d.customerName.split(' ')[0];document.querySelector('#successOrder').textContent=order;const msg=encodeURIComponent(`Hi Peak Finish Automotive, I submitted booking request ${order} for my ${d.make} ${d.model}.`);document.querySelector('#smsLink').href=`sms:0410442507?&body=${msg}`;document.querySelector('#priceDock').hidden=true}catch(err){alert(`We couldn't send your request. Please call 0410 442 507 or try again. ${err.message||''}`);btn.disabled=false;btn.textContent='Send booking request'}});
document.querySelector('#newBooking').addEventListener('click',()=>location.reload());showStep(1);
